# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# Updated with the changes

name: Maven Push

on:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test
      
  trigger-workflow02:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow02
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: KrishnanduLTIMindtree/secondProject
          event-type: trigger-workflow02
          client-payload: '{"TEST_ENV": "QA","CALL_RUN_ID": ${{github.run_id}},"CALL_RUN_NO": ${{github.run_number}},"CALL_WORKFLOW": "${{github.workflow}}"}'
        
          
